[tools]
# Bun
bun = 'latest'

# Deno
deno = '2.3.4'

# Golang
go = 'latest'

# Rust
rust = 'nightly'

# Python
python = 'latest'

# Node.js
'npm:npm' = 'latest'
'npm:pnpm' = 'latest'
'npm:typescript' = 'latest'
'npm:@anthropic-ai/claude-code' = 'latest'
node = ['lts', '23', '24']

[settings]
all_compile = false

